import Head from "next/head"

export default function layout({ children, title, extras }) {
    return (
        <>
            <Head>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <title>{title ? title + " | Neo Chat" : "Neo Chat"}</title>

                <link rel="preconnect" href="https://fonts.googleapis.com" />
                <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
                <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap" rel="stylesheet" />
            </Head>

            <nav></nav>
            <main className="container mx-auto mt-8 max-w-3xl">{children}</main>
            <footer></footer>
        </>
    )
};